name: hockey
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flame: ^1.9.1
  
  cupertino_icons: ^1.0.2
  flame_forge2d: ^0.12.3
  flame_audio: ^1.3.2
  dashbook: ^0.1.11
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/air_hockey_rink.png
    - assets/audio/score_air_horn.mp3
    - assets/audio/charge.mp3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
